routes/web.php
<?php






// Route::post('/logout', 'HomeController@logout')->name('logout');
 Route::get('search', 'HomePageController@table')->name('search');

 Route::get('categories/{category}', 'HomePageController@category')->name('category');
 Route::get('companies/{company}', 'HomePageController@company')->name('company');

 //ajax call
Route::get('myform/ajax/{id}',array('as'=>'myform.ajax','uses'=>'HomePageController@myformAjax'));

//session timed_out
Route::get('/login', 'TimeoutController@timout');

// Authentication Routes...
$this->get('/', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');
//Route::post('/logout', 'HomeController@logout')->name('logout');


// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
//
//    Route::post('logout', ['uses' => 'Auth\LoginController@logout', 'as' => 'logout']);

// Display view
    Route::get('report', 'ReportController@datatable')->name('view/datatables');
// Get Data
    Route::get('datatable/getdata', 'ReportController@getPosts')->name('datatable/getdata');


    Route::get('/home', 'HomeController@index');
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);

    Route::resource('cities', 'Admin\CitiesController');
    Route::post('cities_mass_destroy', ['uses' => 'Admin\CitiesController@massDestroy', 'as' => 'cities.mass_destroy']);
    Route::post('cities_restore/{id}', ['uses' => 'Admin\CitiesController@restore', 'as' => 'cities.restore']);
    Route::delete('cities_perma_del/{id}', ['uses' => 'Admin\CitiesController@perma_del', 'as' => 'cities.perma_del']);

    Route::resource('categories', 'Admin\CategoriesController');
    Route::post('categories_mass_destroy', ['uses' => 'Admin\CategoriesController@massDestroy', 'as' => 'categories.mass_destroy']);
    Route::post('categories_restore/{id}', ['uses' => 'Admin\CategoriesController@restore', 'as' => 'categories.restore']);
    Route::delete('categories_perma_del/{id}', ['uses' => 'Admin\CategoriesController@perma_del', 'as' => 'categories.perma_del']);


    Route::resource('companies', 'Admin\CompaniesController');
    Route::post('companies_mass_destroy', ['uses' => 'Admin\CompaniesController@massDestroy', 'as' => 'companies.mass_destroy']);
    Route::post('companies_restore/{id}', ['uses' => 'Admin\CompaniesController@restore', 'as' => 'companies.restore']);
    Route::delete('companies_perma_del/{id}', ['uses' => 'Admin\CompaniesController@perma_del', 'as' => 'companies.perma_del']);
 
});

app/Company.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Company;
use Illuminate\Http\Request;

/**
 * Class Company
 *
 * @package App
 * @property string $name
 * @property string $city
 * @property string $address
 * @property text $description
 * @property string $logo
*/
class Company extends Model
{
    use SoftDeletes;

    protected $fillable = ['name', 'address', 'description','contact' ,'website','email',
        'logo', 'gender','city_id','gender_type','population','boys','girls','programme','head','contact_head',
        'library_facility','reg_no','date_appointed_head','year_posted','head_dob','magazine','computer','books',
        'library_librarian','librarian_train','email_head'


    ];
    
    public function getImageUrl(){
        return asset($this->logo);
    }
    

    /**
     * Set to null if empty
     * @param $input
     */
    public function setCityIdAttribute($input)
    {
        $this->attributes['city_id'] = $input ? $input : null;
    }
    
    public function city()
    {
        return $this->belongsTo(City::class, 'city_id')->withTrashed();
    }
    
    public function categories()
    {
        return $this->belongsToMany(Category::class, 'category_company')->withTrashed();
    }

    public function scopeFilterByRequest($query, Request $request)
    {
        if ($request->input('city_id')) {
            $query->where('city_id', '=', $request->input('city_id'));
        }

        if ($request->input('categories')) {
            $query->whereHas('categories',
            function ($query) use ($request) {
                $query->where('id', $request->input('categories'));
            });
        }
        
        if ($request->input('search')) {
            $query->where('name', 'LIKE', '%'.$request->input('search').'%');
        }

        return $query;
    }

    public function getTestAttribute() {
        return implode(',', $this->categories->pluck('name')->toArray());
    }

    protected $appends = ['test'];

}

app/Http/Controllers/Admin/CompaniesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreCompaniesRequest;
use App\Http\Requests\Admin\UpdateCompaniesRequest;
use App\Http\Controllers\Traits\FileUploadTrait;

class CompaniesController extends Controller
{
    use FileUploadTrait;

    /**
     * Display a listing of Company.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('company_access')) {
            return abort(401);
        }


        if (request('show_deleted') == 1) {
            if (! Gate::allows('company_delete')) {
                return abort(401);
            }
            $companies = Company::onlyTrashed()->get();
        } else {
            $companies = Company::all();
        }

        return view('admin.companies.index', compact('companies'));
    }

    /**
     * Show the form for creating new Company.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('company_create')) {
            return abort(401);
        }
        
        $cities = \App\City::pluck('name', 'id')->prepend(trans('quickadmin.qa_please_select'), '');
        $categories = \App\Category::pluck('name', 'id');

        return view('admin.companies.create', compact('cities', 'categories'));
    }

    /**
     * Store a newly created Company in storage.
     *
     * @param  \App\Http\Requests\StoreCompaniesRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCompaniesRequest $request)
    {
        if (! Gate::allows('company_create')) {
            return abort(401);
        }
//        dd($request->all());
        $request['head_dob']= date('Y-m-d', strtotime($request->head_dob));
        $request['date_appointed_head']= date('Y-m-d', strtotime($request->date_appointed_head));

        $request = $this->saveFiles($request);
        $company = Company::create($request->all());


        $company->categories()->sync(array_filter((array)$request->input('categories')));

        return redirect()->route('admin.companies.index');
    }


    /**
     * Show the form for editing Company.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('company_edit')) {
            return abort(401);
        }
        
        $cities = \App\City::pluck('name', 'id')->prepend(trans('quickadmin.qa_please_select'), '');
        $categories = \App\Category::pluck('name', 'id');

        $company = Company::findOrFail($id);
//        dd($company);

        return view('admin.companies.edit', compact('company', 'cities', 'categories'));
    }

    /**
     * Update Company in storage.
     *
     * @param  \App\Http\Requests\UpdateCompaniesRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCompaniesRequest $request, $id)
    {
        if (! Gate::allows('company_edit')) {
            return abort(401);
        }
        $request = $this->saveFiles($request);
        $company = Company::findOrFail($id);
        $company->update($request->all());
        $company->categories()->sync(array_filter((array)$request->input('categories')));

        return redirect()->route('admin.companies.index');
    }


    /**
     * Display Company.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('company_view')) {
            return abort(401);
        }
        $company = Company::findOrFail($id);

        return view('admin.companies.show', compact('company'));
    }


    /**
     * Remove Company from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('company_delete')) {
            return abort(401);
        }
        $company = Company::findOrFail($id);
        $company->delete();

        return redirect()->route('admin.companies.index');
    }

    /**
     * Delete all selected Company at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('company_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Company::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }


    /**
     * Restore Company from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        if (! Gate::allows('company_delete')) {
            return abort(401);
        }
        $company = Company::onlyTrashed()->findOrFail($id);
        $company->restore();

        return redirect()->route('admin.companies.index');
    }

    /**
     * Permanently delete Company from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function perma_del($id)
    {
        if (! Gate::allows('company_delete')) {
            return abort(401);
        }
        $company = Company::onlyTrashed()->findOrFail($id);
        $company->forceDelete();

        return redirect()->route('admin.companies.index');
    }


}

resources/views/admin/companies/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')
<style>

</style>
@section('content')
    <h3 class="page-title">@lang('quickadmin.companies.title')</h3>
    @can('company_create')
    <p>
        <a href="{{ route('admin.companies.create') }}" class="btn btn-success">@lang('quickadmin.qa_add_new')</a>
        
    </p>
    @endcan

    @can('company_delete')
    <p>
        <ul class="list-inline">
            <li><a href="{{ route('admin.companies.index') }}" style="{{ request('show_deleted') == 1 ? '' : 'font-weight: 700' }}">@lang('quickadmin.qa_all')</a></li> |
            <li><a href="{{ route('admin.companies.index') }}?show_deleted=1" style="{{ request('show_deleted') == 1 ? 'font-weight: 700' : '' }}">@lang('quickadmin.qa_trash')</a></li>
        </ul>
    </p>
    @endcan


    <div class="panel panel-default" >
        <div class="panel-heading" >
            @lang('quickadmin.qa_list')
        </div>

        <div class="panel-body  table-responsive" >
            <table class="table  table-bordered table-striped {{ count($companies) > 0 ? 'datatable' : '' }} @can('company_delete') @if ( request('show_deleted') != 1 ) dt-select @endif @endcan">
                <thead>
                    <tr>
                        @can('company_delete')
                            @if ( request('show_deleted') != 1 )<th style="text-align:center;"><input type="checkbox" id="select-all" /></th>@endif
                        @endcan

                        <th>@lang('quickadmin.companies.fields.name')</th>
                        <th>@lang('quickadmin.companies.fields.city')</th>
                        <th>@lang('quickadmin.companies.fields.categories')</th>
                        <th>@lang('quickadmin.companies.fields.address')</th>
{{--                        <th>@lang('quickadmin.companies.fields.head')</th>--}}
{{--                        <th>@lang('quickadmin.companies.fields.contact_head')</th>--}}
{{--                        <th>@lang('quickadmin.companies.fields.email_head')</th>--}}
                        <th>@lang('quickadmin.companies.fields.library_facility')</th>
{{--                        <th>@lang('quickadmin.companies.fields.library_librarian')</th>--}}
                        <th>@lang('quickadmin.companies.fields.description')</th>
                        <th>@lang('quickadmin.companies.fields.logo')</th>
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
                    </tr>
                </thead>
                
                <tbody>
                    @if (count($companies) > 0)
                        @foreach ($companies as $company)
                            <tr data-entry-id="{{ $company->id }}">
                                @can('company_delete')
                                    @if ( request('show_deleted') != 1 )<td></td>@endif
                                @endcan

                                <td field-key='name'>{{ $company->name }}</td>
                                <td field-key='city'>{{ $company->city->name or '' }}</td>
                                <td field-key='categories'>
                                    @foreach ($company->categories as $singleCategories)
                                        <span class="label label-info label-many">{{ $singleCategories->name }}</span>
                                    @endforeach
                                </td>
                                <td field-key='address'>{{ $company->address }}</td>
{{--                                <td field-key='head'>{{ $company->head }}</td>--}}
{{--                                <td field-key='contact_head'>{{ $company->contact_head }}</td>--}}
{{--                                <td field-key='email_head'>{{ $company->email_head }}</td>--}}
                                <td field-key='library_facility'>{{ $company->library_facility }}</td>
{{--                                <td field-key='library_librarian'>{{ $company->library_librarian }}</td>--}}
{{--                                <td field-key='librarian_train'>{{ $company->librarian_train }}</td>--}}
                                <td field-key='description'>{!! $company->description !!}</td>
                                <td field-key='logo'>@if($company->logo)<a href="{{ asset(env('UPLOAD_PATH').'/' . $company->logo) }}" target="_blank"><img src="{{ asset(env('UPLOAD_PATH').'/thumb/' . $company->logo) }}"/></a>@endif</td>
                                @if( request('show_deleted') == 1 )
                                <td>
                                    @can('company_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'POST',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.companies.restore', $company->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_restore'), array('class' => 'btn btn-xs btn-success')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                    @can('company_delete')
                                                                        {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.companies.perma_del', $company->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                @endcan
                                </td>
                                @else
                                <td>
                                    @can('company_view')
                                    <a href="{{ route('admin.companies.show',[$company->id]) }}" class="btn btn-xs btn-primary">@lang('quickadmin.qa_view')</a>
                                    @endcan
                                    @can('company_edit')
                                    <a href="{{ route('admin.companies.edit',[$company->id]) }}" class="btn btn-xs btn-info">@lang('quickadmin.qa_edit')</a>
                                    @endcan
                                    @can('company_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("quickadmin.qa_are_you_sure")."');",
                                        'route' => ['admin.companies.destroy', $company->id])) !!}
                                    {!! Form::submit(trans('quickadmin.qa_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                                @endif
                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="11">@lang('quickadmin.qa_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('company_delete')
            @if ( request('show_deleted') != 1 ) window.route_mass_crud_entries_destroy = '{{ route('admin.companies.mass_destroy') }}'; @endif
        @endcan

    </script>
@endsection

resources/views/admin/companies/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('quickadmin.companies.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('quickadmin.qa_view')
        </div>

        <div class="panel-body ">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('quickadmin.companies.fields.name')</th>
                            <td field-key='name'>{{ $company->name }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.companies.fields.city')</th>
                            <td field-key='city'>{{ $company->city->name or '' }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.companies.fields.categories')</th>
                            <td field-key='categories'>
                                @foreach ($company->categories as $singleCategories)
                                    <span class="label label-info label-many">{{ $singleCategories->name }}</span>
                                @endforeach
                            </td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.companies.fields.address')</th>
                            <td field-key='address'>{{ $company->address }}</td>
                        </tr>

                        <tr>
                            <th>@lang('quickadmin.companies.fields.contact')</th>
                            <td field-key='address'>{{ $company->contact }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.companies.fields.website')</th>
                            <td field-key='address'>{{ $company->website }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.companies.fields.email')</th>
                            <td field-key='address'>{{ $company->email }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.companies.fields.reg_no')</th>
                            <td field-key='address'>{{ $company->reg_no }}</td>
                        </tr>
                        @if($company->gender==='single')
                        <tr>
                            <th>@lang('quickadmin.companies.fields.gender')</th>
                            <td field-key='address'>{{ $company->gender .' '.' '.'Sex' }}</td>
                        </tr>
                            <tr>
                            <th>@lang('quickadmin.gender_type')</th>
                            <td field-key='address'>{{ $company->gender_type }}</td>
                        </tr>
                        @elseif($company->gender==='mixed')
                            <tr>
                                <th>@lang('quickadmin.companies.fields.gender')</th>
                                <td field-key='address'>{{ $company->gender .' '.' '.'Sex' }}</td>
                            </tr>
                            <tr>
                                <th>Boys</th>
                                <td field-key='address'>{{ $company->boys}}</td>
                            </tr>
                            <tr>
                                <th>Girls</th>
                                <td field-key='address'>{{ $company->girls}}</td>
                            </tr>
                        @endif
                        <tr>
                            <th>Total Number of Student</th>
                            <td field-key='description'>{!! $company->population !!}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.companies.fields.programme')</th>
                            <td field-key='description'>{!! $company->programme !!}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.companies.fields.head')</th>
                            <td field-key='description'>{!! $company->head !!}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.companies.fields.contact_head')</th>
                            <td field-key='description'>{!! $company->contact_head !!}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.companies.fields.email_head')</th>
                            <td field-key='description'>{!! $company->email_head !!}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.companies.fields.date_appointed_head')</th>
                            <td field-key='description'>{{ date_format(date_create($company->date_appointed_head),'d M Y') }}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.companies.fields.year_posted')</th>
                            <td field-key='description'>{!! $company->year_posted !!}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.companies.fields.head_dob')</th>
                            <td field-key='description'>{{ date_format(date_create($company->head_dob),'d M Y') }}</td>
                        </tr>
                        @if($company->library_facility ==='yes')
                        <tr>
                            <th>@lang('quickadmin.companies.fields.library_facility')</th>
                            <td field-key='description'>{!! $company->library_facility !!}</td>
                        </tr>
                            <tr>
                            <th>@lang('quickadmin.companies.fields.books')</th>
                            <td field-key='description'>{!! $company->books !!}</td>
                        </tr>
                            <tr>
                            <th>@lang('quickadmin.companies.fields.library_librarian')</th>
                            <td field-key='description'>{!! $company->library_librarian !!}</td>
                        </tr>
                            <tr>
                            <th>@lang('quickadmin.companies.fields.librarian_train')</th>
                            <td field-key='description'>{!! $company->librarian_train !!}</td>
                        </tr>
                        @elseif($company->library_facility ==='no')
                            <tr>
                                <th>@lang('quickadmin.companies.fields.library_facility')</th>
                                <td field-key='description'>{!! $company->library_facility !!}</td>
                            </tr>


                        @endif
                        <tr>
                            <th>@lang('quickadmin.companies.fields.magazine')</th>
                            <td field-key='description'>{!! $company->magazine !!}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.companies.fields.computer')</th>
                            <td field-key='description'>{!! $company->computer !!}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.companies.fields.description')</th>
                            <td field-key='description'>{!! $company->description !!}</td>
                        </tr>
                        <tr>
                            <th>@lang('quickadmin.companies.fields.logo')</th>
                            <td field-key='logo'>@if($company->logo)<a href="{{ asset(env('UPLOAD_PATH').'/' . $company->logo) }}" target="_blank"><img src="{{ asset(env('UPLOAD_PATH').'/thumb/' . $company->logo) }}"/></a>@endif</td>
                        </tr>
                    </table>
                </div>
            </div>


            <p>&nbsp;</p>

            <a href="{{ route('admin.companies.index') }}" class="btn btn-default">@lang('quickadmin.qa_back_to_list')</a>
        </div>
    </div>
@stop